# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloader_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.URLlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.URLlineEdit.setGeometry(QtCore.QRect(60, 25, 441, 20))
        self.URLlineEdit.setObjectName("URLlineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.destinationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.destinationLineEdit.setGeometry(QtCore.QRect(70, 70, 351, 20))
        self.destinationLineEdit.setReadOnly(True)
        self.destinationLineEdit.setObjectName("destinationLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(427, 70, 75, 23))
        self.browseButton.setObjectName("browseButton")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 240, 481, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 130, 491, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 160, 491, 16))
        self.titleLabel.setObjectName("titleLabel")
        self.proxyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.proxyCheckBox.setGeometry(QtCore.QRect(460, 200, 51, 17))
        self.proxyCheckBox.setObjectName("proxyCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "URL"))
        self.label_2.setText(_translate("MainWindow", "Destination"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.label_3.setText(_translate("MainWindow", "Select Download:"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#008200;\">Video Title Goes Here</span></p></body></html>"))
        self.proxyCheckBox.setText(_translate("MainWindow", "Proxy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
