# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloader_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.URLlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.URLlineEdit.setGeometry(QtCore.QRect(60, 25, 441, 20))
        self.URLlineEdit.setObjectName("URLlineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.destinationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.destinationLineEdit.setGeometry(QtCore.QRect(70, 70, 351, 20))
        self.destinationLineEdit.setReadOnly(True)
        self.destinationLineEdit.setObjectName("destinationLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(427, 70, 75, 23))
        self.browseButton.setObjectName("browseButton")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 240, 481, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 130, 491, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 160, 491, 16))
        self.titleLabel.setObjectName("titleLabel")
        self.proxyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.proxyCheckBox.setGeometry(QtCore.QRect(460, 200, 51, 17))
        self.proxyCheckBox.setObjectName("proxyCheckBox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 501, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(430, 50, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_6.setObjectName("label_6")
        self.browseButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.browseButton_2.setGeometry(QtCore.QRect(414, 19, 75, 23))
        self.browseButton_2.setObjectName("browseButton_2")
        self.vidPathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.vidPathLineEdit.setGeometry(QtCore.QRect(50, 20, 351, 20))
        self.vidPathLineEdit.setReadOnly(True)
        self.vidPathLineEdit.setObjectName("vidPathLineEdit")
        self.Start = QtWidgets.QLabel(self.groupBox)
        self.Start.setGeometry(QtCore.QRect(110, 50, 16, 16))
        self.Start.setObjectName("Start")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 50, 30, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_4.setObjectName("label_4")
        self.trimButton = QtWidgets.QPushButton(self.groupBox)
        self.trimButton.setGeometry(QtCore.QRect(200, 80, 75, 23))
        self.trimButton.setObjectName("trimButton")
        self.startMinSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.startMinSpinBox.setGeometry(QtCore.QRect(51, 49, 51, 22))
        self.startMinSpinBox.setDisplayIntegerBase(10)
        self.startMinSpinBox.setObjectName("startMinSpinBox")
        self.startSecSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.startSecSpinBox.setGeometry(QtCore.QRect(120, 49, 51, 22))
        self.startSecSpinBox.setObjectName("startSecSpinBox")
        self.endSecSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.endSecSpinBox.setGeometry(QtCore.QRect(439, 50, 50, 22))
        self.endSecSpinBox.setObjectName("endSecSpinBox")
        self.endMinSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.endMinSpinBox.setGeometry(QtCore.QRect(370, 50, 50, 22))
        self.endMinSpinBox.setObjectName("endMinSpinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "URL"))
        self.label_2.setText(_translate("MainWindow", "Destination"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.label_3.setText(_translate("MainWindow", "Select Download:"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#008200;\">Video Title Goes Here</span></p></body></html>"))
        self.proxyCheckBox.setText(_translate("MainWindow", "Proxy"))
        self.groupBox.setTitle(_translate("MainWindow", "Video Trimmer"))
        self.label_9.setText(_translate("MainWindow", ":"))
        self.label_6.setText(_translate("MainWindow", "Start"))
        self.browseButton_2.setText(_translate("MainWindow", "Browse"))
        self.Start.setText(_translate("MainWindow", ":"))
        self.label_7.setText(_translate("MainWindow", "End"))
        self.label_4.setText(_translate("MainWindow", "Video"))
        self.trimButton.setText(_translate("MainWindow", "Trim Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

